### ISSUE TITLE
Audit Storage Capacity

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#11]
- [ ]  Retention time of 1 year with capacity alerts

**Comment by jomolesk** [comment]
Related control(s): AU-4, AU-4 (1), AU-5 (1), AU-11

AU-4: The organization allocates audit record storage capacity in accordance with [Assignment: organization-defined audit record storage requirements]. **NOTE: This control is related to AU-11, which requires audit records be retained for 1 year. This will likely be accomplished by offloading audit data to OMS for that retention period. Local audit storage capacity should be configured accordingly; OMS audit storage capacity should be configured to retain for a minimum of 1 year.** [_This Azure Blueprint Solution allocates sufficient storage capacity to retain audit records for a period of one year._] (Also see issue #16.)

AU-4 (1): The information system off-loads audit records [Assignment: organization-defined frequency] onto a different system or media than the system being audited. [_This Azure Blueprint Solution forwards audit records to OMS..._] (Also see issue #16.)

AU-5 (1): The information system provides a warning to [Assignment: organization-defined personnel, roles, and/or locations] within [Assignment: organization-defined time period **(real-time)**] when allocated audit record storage volume reaches [Assignment: organization-defined percentage **(90%)**] of repository maximum audit record storage capacity. [_**need implementation details**_] (Also see issue #16.)

AU-11: The organization retains audit records for [Assignment: **at least one year**] to provide support for after-the-fact investigations of security incidents and to meet regulatory and organizational information retention requirements. [_This Azure Blueprint Solution implements OMS Log Analytics. Log Analytics provides monitoring services for OMS by collecting data from managed resources into a central repository. Once collected, the data retained for one year per Log Analytics configuration..._] (Also see issue #16.)

**Comment by jomolesk** [comment]
@bhavyasinghal is this the solution you were referencing? I don't immediately see anything that would prevent this from being customized to run in gov, but someone will need to validate https://github.com/Azure/azure-quickstart-templates/tree/master/oms-azure-storage-analytics-solution

**Comment by bhavyasinghal** [comment]
@jomolesk Yes I am referencing this solution only.

**Comment by bhavyasinghal** [comment]
@davoodharun: The solution was added in this existing json file: https://github.com/AppliedIS/azure-blueprint/blob/testing/nestedtemplates/provisioningNetworkStorageAGSet.json

**Comment by bhavyasinghal** [comment]
Once this is merged with the final template:

@reetikatech 
Testing instructions:
In azure resource group:
1) Find storage accounts. In each storage account-> go to alert rules.
2) You will an alert rule, The status should be on:
        "name": "capacity alert",
        "description": "usage more than 450 TB"
