### ISSUE TITLE
Audit system failure (action / alerts)

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#12]

**Comment by jomolesk** [comment]
Related control(s); AU-5.a, AU-5.b, AU-5 (2)

AU-5.a: The information system alerts [Assignment: organization-defined personnel or roles] in the event of an audit processing failure. [_**need implementation details**_]

AU-5.b: The information system takes the following additional actions: [Assignment: organization-defined actions to be taken (**overwrite oldest audit records**)]. [_**need implementation details**_]

AU-5 (2): The information system provides an alert in [**real-time**] to [Assignment: organization-defined personnel, roles, and/or locations] when the following audit failure events occur: [Assignment: organization-defined audit failure events requiring real-time alerts]. [_**need implementation details**_]

**Comment by bhavyasinghal** [comment]
@jomolesk Hi, Can the scope of this task be elaborated?

**Comment by jomolesk** [comment]
This can be scoped mostly to the OS-level: configure Windows auditing to overwrite oldest audit records if disk space is low and generate an alert -- perhaps via a Log Analytics log search alert in OMS. This control may also be implemented via the Azure Storage Analytics solution (from issue #11) for the storage account where the logs are later collected.

**Comment by bhavyasinghal** [comment]
@jomolesk Thanks. Will look into this.

**Comment by bhavyasinghal** [comment]
Added alerts in oms-workspace itself:

https://github.com/AppliedIS/azure-blueprint/tree/testing/blocks/oms-workspace-deploy

**Comment by bhavyasinghal** [comment]
@davoodharun  solution included in template for issue #10 
here: https://github.com/AppliedIS/azure-blueprint/tree/testing/blocks/oms-workspace-deploy
