### ISSUE TITLE
Restrictions on audit configurations / tools (who can configure / view)

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#14]

**Comment by jomolesk** [comment]
Related control(s): AU-9, AU-9 (4)

AU-9: The information system protects audit information and audit tools from unauthorized access, modification, and deletion. [_Logical access controls are used to protect audit information and tools within this Azure Blueprint Solution from unauthorized access, modification, and deletion. Azure Active Directory enforces approved logical access using Active Directory policies and role-based group memberships. The ability to view audit information and use auditing tools is limited to users that require these permissions._] **need to address at the OS-level, for OMS, and anywhere else audit data is available** (Also see issue #13, #19.)

AU-9 (4): The organization authorizes access to management of audit functionality to only [Assignment: organization-defined subset of privileged users]. [_Azure Active Directory restricts the management of audit functionality to members of the appropriate security groups. Only personnel with a specific need to access the management of audit functionality are granted these permissions within this Azure Blueprint Solution._] (Also see issue #19.)

**Comment by manishkumar-agarwal** [comment]
Hi @jomolesk @davoodharun 

There are two ways with which access can be controlled for OMS. 
a) Providing access in the OMS portal. This access details are provided locally. The owner creating the OMS workspace is provided with an Administrator access by default

b) Access provided for users using the Azure RBAC. We would be able to use the "Log Analytics Reader" and "Log Analytics Contributor" role

As part of this assignment, we would be able to provide script for assigning users this role based on access. "Log Analytics Reader" and "Log Analytics Contributor" would differentiate the separation of roles

Please let me know if above is sufficient or there any other tasks to be covered for this one.

Thanks

**Comment by jomolesk** [comment]
Hi @manishkumar-agarwal -- the solution you described sounds sufficient to meet the control requirement.

**Comment by manishkumar-agarwal** [comment]
As part of this request, the user activities have been verified in a standalone OMS solution using the Azure provided "Log Analytics Reader" and "Log Analytics Contributor" Role. 

User access was restricted when providing "Log Analytics Reader" to only writing queries.

 "Log Analytics Contributor" Role was allowing the user to add VM's, storages, subscriptions and also query OMS.

The same needs to be verified in the final deployment
