### ISSUE TITLE
Time sync

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#15]
- [ ] 1 second
- [ ] UTC

**Comment by jomolesk** [comment]
Related control(s): AU-8.a, AU-8.b, AU-8 (1).a, AU-8 (1).b

AU-8.a: The information system uses internal system clocks to generate time stamps for audit records. [_Resources deployed by this Azure Blueprint Solution use internal system clocks to generate time stamps for audit records._] **NOTE: Need to address all components that generate audit records.**

AU-8.b: The information system records time stamps for audit records that can be mapped to Coordinated Universal Time (UTC) or Greenwich Mean Time (GMT) and meets [Assignment: organization-defined granularity of time measurement **(one second)**]. [_Resources deployed by this Azure Blueprint Solution use internal system clocks to generate time stamps for audit records. Time stamps are recorded in UTC._] **NOTE: Need to address all components that generate audit records.**

AU-8 (1).a: The information system compares the internal information system clocks [Assignment: **at least hourly**] with [Assignment: **http://tf.nist.gov/tf-cgi/servers.cgi**]. [_Resources deployed by this Azure Blueprint Solution use internal system clocks to generate time stamps for audit records. Internal system clocks are configured to sync with an authoritative time source each hour._] **NOTE: Need to address all components that generate audit records.**

AU-8 (1).b: The information system synchronizes the internal system clocks to the authoritative time source when the time difference is greater than [Assignment: organization-defined time period]. [_Resources deployed by this Azure Blueprint Solution use internal system clocks to generate time stamps for audit records. Internal system clocks are configured to sync with an authoritative time source each hour._] **NOTE: Need to address all components that generate audit records.**

**Comment by bhavyasinghal** [comment]
@jomolesk Can you help with specifying- what time sync-1 second is?

**Comment by jomolesk** [comment]
@bhavyasinghal All system clocks must be synchronized to within one second of each other.

**Comment by bhavyasinghal** [comment]
@davoodharun 
For issue #15
The PowerShell script that sets windows VM time sync to UTC is kept here in testing blocks: https://github.com/AppliedIS/azure-blueprint/blob/testing/blocks/SetTimeZone/SetTimeZone.ps1

It needs to run while Custom script extensions are running on all VMs/Or while provisioning the VMs.
Can this be included in the original template? where should I place this?

**Comment by bhavyasinghal** [comment]
https://github.com/AppliedIS/azure-blueprint/tree/testing/blocks/SetTimeZone
