### ISSUE TITLE
Patching

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#23]
- [x] Windows update configured
- [x] Dashboard reporting in OMS

**Comment by jomolesk** [comment]
Related controls: SI-2.a, SI-2.c, SI-2 (1), SI-2 (2)

SI-2.a: The organization identifies, reports, and corrects information system flaws. [_This Azure Blueprint Solution deploys the OMS Automation & Control solution to track the status of updates for the Windows virtual machines deployed in this architecture. From the OMS dashboard, the Update Management tile displays flaw remediation status for all deployed Windows servers._]

SI-2.c: The organization installs security-relevant software and firmware updates within [Assignment: **30 days**] of the release of the updates. [_Windows virtual machines deployed by this Azure Blueprint Solution are configured by default to receive automatic updates from Windows Update Service. This solution also deploys the OMS Automation & Control solution through which Update Deployments can be created to deploy patches to Windows servers when needed._] (Also see issue #21.)

SI-2 (1): The organization centrally manages the flaw remediation process. [_This Azure Blueprint Solution deploys the OMS Automation & Control solution to track the status of updates for the Windows virtual machines deployed in this architecture. From the OMS dashboard, the Update Management tile displays flaw remediation status for all deployed Windows servers. Update Deployments can be created to deploy patches to Windows servers when needed._]

SI-2 (2): The organization employs automated mechanisms [Assignment: **monthly**] to determine the state of information system components with regard to flaw remediation. [_This Azure Blueprint Solution deploys the OMS Automation & Control solution to track the status of updates for the Windows virtual machines deployed in this architecture. For each managed Windows computer, a scan is performed twice per day. Every 15 minutes the Windows API is called to query for the last update time to determine if status has changed, and if so a compliance scan is initiated._]

**Comment by reetikatech** [comment]
in Friday's call this was on discussion that OMS issues were not fixed and still working on the same after that no update was received if working or resolved? also not having clarity of expected Result.
please let me know the expected Result.

**Comment by dciceman** [comment]
Please following the steps below for testing

Step 1- Verify Automation Jobs are created and running 
	1. Login to Azure
	2. Select your resource group from Resource group list 
	3. Click on Overview -> Automation Account
	4. Click on Hybrid Worker Groups under Resources (Verify all VMs display under the Group Name column)
	5. Click on Job Statistics under Monitoring (Verify all jobs completed successfully. Once job per VM)
	6. Click on Schedules under Shared Resources (Verify VM-Patching Schedule is created and running daily)
	
Step 2 - Verify All VM have been updated from OMS Portal 
	1. Login to Azure
	2. Select your resource group from Resource group list 
	3. Click on Overview -> OMS workspace name (Type: Log Analytics)
	4. Click on OMS Portal
	5. Microsoft Operations Management Suite opens
	6. Click on the Update Management Solution
	7. Windows Updates under Missing Updates should display 0 Critical Updates and 0 security Updates

**Comment by reetikatech** [comment]
OMS is not deployed yet ,we can proceed with the following steps only after OMS deployment.
