### ISSUE TITLE
Redundant storage (geo-replicated)

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#26]
backup data

**Comment by jomolesk** [comment]
Related control(s): CP-6.a, CP-6.b, CP-6 (1), CP-6 (2)

CP-6.a: The organization establishes an alternate storage site including necessary agreements to permit the storage and retrieval of information system backup information. [_All storage accounts deployed by this Azure Blueprint Solution are replicated to ensure high availability using geo-redundant storage (GRS). GRS ensures that data is replicated to a secondary region._]

CP-6.b: The organization ensures that the alternate storage site provides information security safeguards equivalent to that of the primary site. [_All storage accounts deployed by this Azure Blueprint Solution are replicated to ensure high availability using geo-redundant storage (GRS). Physical security controls are implemented uniformly across Azure datacenters._]

CP-6 (1): The organization identifies an alternate storage site that is separated from the primary storage site to reduce susceptibility to the same threats. [_All storage accounts deployed by this Azure Blueprint Solution are replicated to ensure high availability using geo-redundant storage (GRS). GRS ensures that data is replicated to a secondary region. Primary and secondary regions are paired to ensure necessary distance between datacenters to ensure availability in the event of an area-wide outage or disaster._]

CP-6 (2): The organization configures the alternate storage site to facilitate recovery operations in accordance with recovery time and recovery point objectives. [_All storage accounts deployed by this Azure Blueprint Solution are replicated to ensure high availability using geo-redundant storage (GRS). GRS ensures that data is replicated to a secondary region._]

**Comment by davoodharun** [comment]
@jomolesk is this as simple as using GRS for all storage account types?

**Comment by jomolesk** [comment]
In this architecture, yes, I believe it's sufficient.

**Comment by davoodharun** [comment]
Closing this per #51

**Comment by davoodharun** [comment]
This issue is resolved by using Standard_GRS storage types for all storage accounts.

**Comment by reetikatech** [comment]
verified  by Reetka all storage accounts using Standard__Geo-redundant Storage(GRS).
![image](https://cloud.githubusercontent.com/assets/26430269/26440389/bc388f08-4149-11e7-9458-ee193cc59ab7.png)
