### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#27]
- [x] User-level
- [x] System-level
- [x] Encrypted (SSE)
- [x] Dashboard reporting

**Comment by jomolesk** [comment]
Related control(s): CP-9.a, CP-9.b, CP-9.d, CP-9 (5)

CP-9.a: The organization conducts backups of user-level information contained in the information system [Assignment: **daily incremental; weekly full**]. [_This Azure Blueprint Solution deploys Azure Backup for all virtual machines. All deployed storage accounts within this Azure Blueprint Solution implement geo-redundant storage, ensuring six copies of all data are maintained on separate nodes across two data centers._]

CP-9.b: The organization conducts backups of system-level information contained in the information system [**daily incremental; weekly full**]. [_This Azure Blueprint Solution deploys Azure Backup for all virtual machines. All deployed storage accounts within this Azure Blueprint Solution implement geo-redundant storage, ensuring six copies of all data are maintained on separate nodes across two data centers._]

CP-9.d: The organization protects the confidentiality, integrity, and availability of backup information at storage locations. [_Confidentiality and integrity of all storage blobs deployed by this Azure Blueprint Solution are protected through use of Azure SSE, which uses 256-bit AES encryption for all data-at-rest._]

CP-9 (5): The organization the organization transfers information system backup information to the alternate storage site [Assignment: organization-defined time period and transfer rate consistent with the recovery time and recovery point objectives]. [_All deployed storage accounts within this Azure Blueprint Solution, including those used for backup, implement geo-redundant storage, ensuring six copies of all data are maintained on separate nodes across two data centers._]

**Comment by JustinBacaAIS** [comment]
+ [x] Created Recovery Services Vault Template (Complete/Deploy-Success)
+ [x] Created ProtectedItems Template (Complete/Deploy-Success)
+ [x] Create Backup Policy Template (Complete/Deploy-Success)
+ [x] Merge/Implement Azure Disk Encryption Extension

**Comment by reetikatech** [comment]
verified  on Resurce grp: Bprint700
recovery services Vault
Protected items template
backup policy template
Not found Azure Disk Encryption Extension
will discuss with Justin to proceed.
![image](https://cloud.githubusercontent.com/assets/26430269/26244462/5ab0b328-3cad-11e7-8dc5-b068221cb951.png)

**Comment by JustinBacaAIS** [comment]
# Backup
## Recovery Services Vault
- **Name**: AZ-RCV-01
- **Protected Items**: All VMs
## Backup Policy
- **Name**: CustomPolicy
- **Backup frequency**: Daily 7:00PM
- **Daily Retention**: 30 Days
- **Weekly Retention**: Sunday for 104 weeks
- **Monthly Retention**: Day based 1st of month for 36 months
- **Yearly Retention**: Day based 1st of January for 5 years
## Encryption
- Implemented using the **Azure Disk Encryption Extension**
## System Level Backup
- Implemented using protectedItem resource deployment and **CustomPolicy**
## User Level Backup
- Implemented using **SQL VM IaaS Extension**
- **Enable**: true, 
- **RetentionPeriod**: 30 
- **EnableEncryption**: true, 
- **BackupScheduleType**: Manual, 
- **FullBackupFrequency**: Weekly, 
- **FullBackupStartTime**: 2, 
- **FullBackupWindowHours**: 2, 
- **LogBackupFrequency**: 60

**Comment by reetikatech** [comment]
verified Backup policy:
Observation: 
currently this displays all VMs of all Resource Groups to select, what is the expectation: it has to display VMs of only that resource group its belong to or all of the subscription's all vms.

![image](https://cloud.githubusercontent.com/assets/26430269/26528161/201d934a-43c2-11e7-9442-a7f9326a952f.png)


![image](https://cloud.githubusercontent.com/assets/26430269/26528190/e901ed24-43c2-11e7-8195-9523214bf8ad.png)
