### ISSUE TITLE
Information flow enforcement

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#30]
- [ ] SQL tier to db tier
- [ ] Management

**Comment by jomolesk** [comment]
Related control(s): AC-4

AC-4: The information system enforces approved authorizations for controlling the flow of information within the system and between interconnected systems based on [Assignment: organization-defined information flow control policies]. Information flow control regulates where information is allowed to travel within an information system and between information systems (as opposed to who is allowed to access the information) and without explicit regard to subsequent accesses to that information. Flow control restrictions include, for example, blocking outside traffic that claims to be from within the organization, restricting web requests to the Internet that are not from the internal web proxy server. Enforcement occurs, for example, in boundary protection devices (e.g., gateways, routers, guards, encrypted tunnels, firewalls) that employ rule sets or establish configuration settings that restrict information system services, provide a packet-filtering capability based on header information, or message-filtering capability based on message content (e.g., implementing key word searches or using document characteristics). [This Azure Blueprint Solution enforces information flow restrictions [...].]

**Comment by jomolesk** [comment]
Useful reference; we want to achieve something similar and document accordingly (relevant to issue #31 as well): https://github.com/mayurshintre/Blueprints-PaaS-ASE/blob/master/ase-ilb-blueprint/README.md#23-security

**Comment by reetikatech** [comment]
#53 is verified and closed already and is as expected.
its is referenced in the same #30
if any more expectation in #30 please elaborate here with Expected Result.
