### ISSUE TITLE
Information at rest

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#35]
- [x] BitLocker
- [x] SSE
- [x] Backup

**Comment by jomolesk** [comment]
Related controls: SC-28, SC-28 (1)

SC-28: The information system protects the [Selection: **confidentiality and integrity**] of [Assignment: organization-defined information at rest]. [_SC-28 (1) implementation satisfies this control requirement._]

SC-28 (1): The information system implements cryptographic mechanisms to prevent unauthorized disclosure and modification of [Assignment: organization-defined information] on [Assignment: **all information system components storing customer data deemed sensitive**]. [_Virtual machines deployed by this Azure Blueprint Solution implement disk encryption to protect the confidentiality and integrity of information at rest. Azure disk encryption for Windows is implemented using the BitLocker feature of Windows. SQL Database is configured to use Transparent Data Encryption (TDE), which performs real-time encryption and decryption of data and log files to protect information at rest. TDE provides assurance that stored data has not been subject to unauthorized access. Customer may elect to implement additional application-level controls to protect the integrity of stored information. Confidentiality and integrity of all storage blobs deployed by this Azure Blueprint Solution (including those used for backup, log storage **list all deployed storage account uses**) are protected through use of Azure Storage Service Encryption (SSE). SSE safeguards data at rest within Azure storage accounts using 256-bit AES encryption._] (Also see issue #22.)

**Comment by reetikatech** [comment]
please mention here how I can check the expectation.

**Comment by jomolesk** [comment]
- all storage accounts use SSE
- all VM disks are encrypted
- SQL using TDE

**Comment by reetikatech** [comment]
Verified by Reetika
All storage accounts are using SSE
All VM Disks are not encrypted
SQL using TDE

![image](https://cloud.githubusercontent.com/assets/26430269/26444262/54555d2a-4159-11e7-8739-761d41371328.png)

**Comment by JustinBacaAIS** [comment]
@davoodharun 
Azure Disk Encryption creates BEK volume on disk 2 formatted with MBR.  This conflicts with the PDC and BDC DSC resources that have static disk number set to 2, which when run after initial deployment will fail due to disk 2 already being initialized.  Need to add a validation step for the F:\ volume to identify which disk the volume is a part of.  Was able to track down some PS to assist in accomplishing this.

Get-WmiObject Win32_DiskDrive | % {
  $disk = $_
  $partitions = "ASSOCIATORS OF " +
                "{Win32_DiskDrive.DeviceID='$($disk.DeviceID)'} " +
                "WHERE AssocClass = Win32_DiskDriveToDiskPartition"
  Get-WmiObject -Query $partitions | % {
    $partition = $_
    $drives = "ASSOCIATORS OF " +
              "{Win32_DiskPartition.DeviceID='$($partition.DeviceID)'} " +
              "WHERE AssocClass = Win32_LogicalDiskToPartition"
    Get-WmiObject -Query $drives | % {
      New-Object -Type PSCustomObject -Property @{
        Disk        = $disk.DeviceID
        DiskSize    = $disk.Size
        DiskModel   = $disk.Model
        Partition   = $partition.Name
        RawSize     = $partition.Size
        DriveLetter = $_.DeviceID
        VolumeName  = $_.VolumeName
        Size        = $_.Size
        FreeSpace   = $_.FreeSpace
      }
    }
  }
}

**Comment by reetikatech** [comment]
verified VM disks for encryption enable its enabled now. as expected.
![image](https://cloud.githubusercontent.com/assets/26430269/26483570/59b047be-420b-11e7-9fdc-337ca0f20a55.png)

**Comment by jmmcnj** [comment]
closing per @reetikatech verification
