### ISSUE TITLE
Azure Commercial support

### ISSUE THREAD

**Issue by bhavyasinghal** [AppliedIS/azure-blueprint#38]
Hi Harun,

I am facing errors in the template- it errors out while provisioning the virtual machines:
![1](https://cloud.githubusercontent.com/assets/15995370/25484237/da73c7c8-2b76-11e7-9d4d-a65e157f9363.JPG)

When I looked at the template from where it is provisioning the diagnostic storage account- it is giving the URI as “blob.core.usgovcloudapi.net” 
![2](https://cloud.githubusercontent.com/assets/15995370/25484242/e0275680-2b76-11e7-902d-efdf5eb3ee60.JPG)

Please let me know what to do.

Thanks
Bhavya

**Comment by bhavyasinghal** [comment]
As dicussed-This is only supposed to work for Azure Gov tenants, thats why its failing in MSDN subscription.

Closing the issue.

Bhavya

**Comment by davoodharun** [comment]
@bhavyasinghal I'm not entirely sure of all the differences are between Azure commercial and Azure Gov, but I know that the storage account uri's is one difference. I will try and abstract the storage account uri suffix as a parameter  and give the user the option to choose between gov & commercial. However, this is lower on the list of priorities.

**Comment by bhavyasinghal** [comment]
@davoodharun  Understood.

**Comment by NateJohnson1** [comment]
If we can make this a check-box type option then selecting the environment by the customer is fine. We do not want the customer to have to know or enter that full URI. Note there will be additional changes that we would have to bundle into that selection option if we have a toggle for both Comm/Gov.  

This page includes the storage-specific URI changes for commercial/gov:

https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-services-storage

**Comment by davoodharun** [comment]
Im going to reopen this just so its visible
