### ISSUE TITLE
Add Application Gateway for Web Tier

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#4]

**Comment by jomolesk** [comment]
Web tier to use Application Gateway.

**Comment by davoodharun** [comment]
@jomolesk I can't remember off the top of my head without testing this out, but do you know if the application gateway can be provisioned before the VMs that are associated with it are created (if we can predict the allocation of the IP addresses of all the machines)?  Im asking because with my experience the gateway takes over 40 minutes to complete provisioning and would add a significant amount of deployment time if it was provisioned after all the VMs were created.

**Comment by jomolesk** [comment]
I believe that you can. Deployment time may have improved; I did a test recently and I don't recall it taking that long. Deployment speed is secondary to functionality; but we need to justify every minute. Once the solution is stabilized, I'd like to have a timeline graph showing the deployment process over time; something like:
`0----5----10----15----20----25----30----35----40----45----50----55----60----`
`[--VM1--]`
`[--VM2--]`
`.......[--Application gateway--]`
`..............................................[--post deploy configuration--]`
