### ISSUE TITLE
SQL AO extension timeout while deploying template

### ISSUE THREAD

**Issue by bhavyasinghal** [AppliedIS/azure-blueprint#41]
The template errored out while installing extension on SQLAO VM with message- "Provisioning of VM extension 'sqlAOPrepare' has timed out. Extension installation may be taking too long, or extension status could not be obtained.

This was while deploying the template for Azure commercial subscription. I forked the azure-blueprint directory to my own github repo and changed the values to deploy in an azure non-gov subscription.

Rest of the deployment succeeded.

![3](https://cloud.githubusercontent.com/assets/15995370/25522859/1862d320-2c22-11e7-897b-d45ae181d49b.JPG)

**Comment by bhavyasinghal** [comment]
![4](https://cloud.githubusercontent.com/assets/15995370/25523165/4d95aa58-2c23-11e7-8b80-87aea1a598aa.JPG)

**Comment by davoodharun** [comment]
@bhavyasinghal can you see if you are still experiencing this issue?

**Comment by bhavyasinghal** [comment]
@davoodharun Experiencing the same issue- Extension time out in 1 hour 35 minutes 49 seconds

**Comment by davoodharun** [comment]
@bhavyasinghal I am going to close this issue since you are testing in the commercial environment. I @JustinBacaAIS and I have tested this several times without error. We can re-open on request.
