### ISSUE TITLE
password validation not working for keyvault creation

### ISSUE THREAD

**Issue by reetikatech** [AppliedIS/azure-blueprint#49]
while running powershell script for keyvault. 
given password in simple string ie. reetikatech and its accepted and created successfully. without validation check mentioned in #7.
  also displayed error on powershell screen but still created key vault.

**Comment by davoodharun** [comment]
@reetikatech I am going to close this issue since this is related to the running of the script and not the actual implementation. we can address the implementation in #7

**Comment by reetikatech** [comment]
currently its implemented for complexity check, initial strong password and 
no check for special character.
not implemented for entropy. 
just for record
