### ISSUE TITLE
Unique identifiers (e.g., no “Administrator”)

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#6]

**Comment by davoodharun** [comment]
I believe this control is already met by default. Windows will force you to rename the administrator account. Are there any other unique identifiers or is "Administrator" the only one?

**Comment by jomolesk** [comment]
Related control(s): IA-2, IA-4.d

IA-2: The information system uniquely identifies and authenticates organizational users (or processes acting on behalf of organizational users). [_Accounts created by this Azure Blueprint Solution have unique identifiers. Built-in accounts with non-unique identifiers are disabled or removed._]

IA-4.d: The organization manages information system identifiers by preventing reuse of identifiers for [Assignment: **at least two years**]. [_Unique user identifiers are never reused. This is enforced by Azure Active Directory / Active Directory / Windows Server._]

**Comment by reetikatech** [comment]
uniqueness is on which basis ie. user name or emailids or combination. I mean are we imposing unique id on email id or user name. for example: 
account with different username but with same emailed can exist?   or 
accounts with same username with multiple emailed can exist.

**Comment by jomolesk** [comment]
Accounts w/ different usernames associated with the same email address are ok.

**Comment by davoodharun** [comment]
Accounts created:
Local admin, Domain admin
Sql Service

**Comment by davoodharun** [comment]
# Unique Identifiers 
Accounts created by this Azure Blueprint Solution have unique identifiers. Built-in accounts with non-unique identifiers are disabled or removed.

Unique user identifiers are never reused. This is enforced by Azure Active Directory / Active Directory / Windows Server.
