### ISSUE TITLE
Not dispalying connected servers under AZ-MGT-VM

### ISSUE THREAD

**Issue by reetikatech** [AppliedIS/azure-blueprint#60]
Resource group: bPrint700
Steps:
Remote desktop login to AZ-MGT-VM publicip: 57.227.167.226

observation:
 yesterday:
when previously logged in its displaying all Servers under MGT server,using resource group Blueprint40.
today :resource group bprint700 displaying no servers under MGT server.

![image](https://cloud.githubusercontent.com/assets/26430269/26242708/fbb85dea-3ca6-11e7-8d8e-b0afbc044cd4.png)

**Comment by davoodharun** [comment]
Even though the machines are joined to the domain, they do not show up on this screen. You have to manually add them through the dashboard.
