### ISSUE TITLE
Password Restriction Error in Pre Deploying AzureDeploy Script on using expected Password String also

### ISSUE THREAD

**Issue by reetikatech** [AppliedIS/azure-blueprint#63]
Steps:
Followed the same steps provided by Harun on Code page to deploy AzureDeploy script
 while setting up pre-deployment setup 
throwing Password Complexity Error: Administrator password did not meet the complexity requirements
on using expected Password string also throwing same error and not letting to proceed.

screenshot below
![image](https://cloud.githubusercontent.com/assets/26430269/26341767/ec2efac8-3fb2-11e7-9b6c-905ed7e583a9.png)

**Comment by davoodharun** [comment]
which branch are you running this from? you should be running from the testing branch  as we have made improvements to the script

**Comment by reetikatech** [comment]
Yes on using Code from testing branch:
Screenshot:
[cid:image001.jpg@01D2D3C1.C3977E80]

**Comment by reetikatech** [comment]
![image](https://cloud.githubusercontent.com/assets/26430269/26342291/1b4bcf46-3fb5-11e7-9171-b98b103e631f.png)

**Comment by davoodharun** [comment]
thanks @reetikatech I will take a look

**Comment by davoodharun** [comment]
I was able to run it successfully -- I updated the README on the testing branch to reflect proper instructions. Let me know if you are still experiencing this issue after going through those instructions

**Comment by reetikatech** [comment]
Able to run and deploy  in new resource group with provided steps it was successfully deployed yesterday for today displaying below error in template
Deployment template validation failed: 'The value for the template parameter 'wafEnabled' at line '50' and column '20' is not provided. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'. 
![image](https://cloud.githubusercontent.com/assets/26430269/26390709/5ebb5922-407d-11e7-9164-e123a31a1fd6.png)

(Code: InvalidTemplate)
![image](https://cloud.githubusercontent.com/assets/26430269/26390417/1f15d028-407c-11e7-88ad-1f4471ff6542.png)
