### ISSUE TITLE
All VM Disks are not encrypted

### ISSUE THREAD

**Issue by reetikatech** [AppliedIS/azure-blueprint#67]
in reference to the issue #35 information at rest
issue All Diskes should be encrypted
steps: 
Checked disk encryption of all VMs
Expected : encrypted
Actual: not encrypted
![image](https://cloud.githubusercontent.com/assets/26430269/26444733/2c55f8fa-415b-11e7-894a-eb0ab7654c43.png)

**Comment by JustinBacaAIS** [comment]
@reetikatech 
The deployment failed on this resource group before reaching the Azure Disk Encryption extension on that VM.

**Comment by reetikatech** [comment]
verified the issue in Resource group BP2 as per the communication with Justin.
its displaying as expected
screenshot below
![image](https://cloud.githubusercontent.com/assets/26430269/26527128/d7b247ca-43aa-11e7-80b4-5027198529e5.png)
hence closed
