### ISSUE TITLE
Pre-deploy scrip password complexity checking broken

### ISSUE THREAD

**Issue by jomolesk** [AppliedIS/azure-blueprint#86]
For example, asdfASDF1234!@#$ is returning an error:
![image](https://user-images.githubusercontent.com/23081194/27052570-1173dc92-4f88-11e7-9ca7-8a4b7ff1185c.png)

Can we update this script so that the password is checked inline? As it works now, if a non-compliant password is entered, the user isn't informed until ALL parameters are entered. Then they have to completely re-run the script.

**Comment by davoodharun** [comment]
@jomolesk I updated the script. Now you are prompted for each password in the beginning of the script. Password validation is also done after each password is entered. Can you confirm if this works for you?

**Comment by jomolesk** [comment]
![image](https://user-images.githubusercontent.com/23081194/27084811-3b78e472-501b-11e7-9dd0-4299a369f878.png)
