### ISSUE TITLE
Key Management / Key Vault

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#9]
Related to #39
- [ ] BitLocker
- [ ] SQL encryption - [URL for TDE to enable SQL encryption](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption-tde)

**Comment by jomolesk** [comment]
Related control(s): IA-5.h, IA-5.i, IA-5 (7), SC-12, SC-12 (1), SC-12 (2)

IA-5.h: The organization manages information system authenticators by protecting authenticator content from unauthorized disclosure and modification. [_This Azure Blueprint Solution implements Key Vault to protect authenticator content from unauthorized disclosure and modification. **The following authenticators are stored in Key Vault: TBD**._]

IA-5.i: The organization manages information system authenticators by requiring individuals to take, and having devices implement, specific security safeguards to protect authenticators. [_This Azure Blueprint Solution implements Key Vault to protect authenticator content from unauthorized disclosure and modification. **The following authenticators are stored in Key Vault: TBD.** Key Vault encrypts keys and secrets (such as authentication keys, storage account keys, data encryption keys, and passwords) by using keys that are protected by hardware security modules (HSMs)._]

IA-5 (7): The organization ensures that unencrypted static authenticators are not embedded in applications or access scripts or stored on function keys. [_There is no use of unencrypted static authenticators embedded in applications, access scripts, or function keys deployed by this Azure Blueprint Solution. Any script or application that uses an authenticator makes a call to an Azure Key Vault container prior to each use. Access to Azure Key Vault containers is audited, which allows detection of violations of this prohibition if a service account is used to access a system without a corresponding call to the Azure Key Vault container._] (Also see issue #7.)

SC-12: The organization establishes and manages cryptographic keys for required cryptography employed within the information system in accordance with [Assignment: organization-defined requirements for key generation, distribution, storage, access, and destruction]. [_This Azure Blueprint Solution deploys an Azure Key Vault. Azure Key Vault helps safeguard cryptographic keys and secrets used by cloud applications and services. Azure Key Vault can generate keys using a FIPS 140-2 level 2 hardware security module (HSM) key generation capability._]

SC-12 (1): The organization maintains availability of information in the event of the loss of cryptographic keys by users. [_Azure Key Vault is used to store cryptographic keys and secrets used in this Azure Blueprint Solution. Key Vault streamlines the key management process for keys that access and encrypt data. **The following authenticators are stored in Key Vault: TBD.**_]

SC-12 (2): The organization produces, controls, and distributes symmetric cryptographic keys using [Selection: **NIST FIPS-compliant**] key management technology and processes. [_Azure Key Vault is used to produce, control, and distribute cryptographic keys. Azure Key Vault can generate keys using a FIPS 140-2 level 2 hardware security module (HSM) key generation capability. Keys are stored and managed within securely encrypted containers within Azure Key Vault._]

**Comment by davoodharun** [comment]
closing this per #44. 

Bit Locker will be addressed by #35 
TDE will be addressed by #28

**Comment by davoodharun** [comment]
Azure username
Azure Password
Azure AD Client ID
Azure AD Client Secret
SQL service Password

**Comment by davoodharun** [comment]
# Key Vault / Key Management
This Azure Blueprint Solution implements Key Vault to protect authenticator content from unauthorized disclosure and modification. Azure Key Vault helps safeguard cryptographic keys and secrets used by cloud applications and services. Azure Key Vault can generate keys using a FIPS 140-2 level 2 hardware security module (HSM) key generation capability.

There is no use of unencrypted static authenticators embedded in applications, access scripts, or function keys deployed by this Azure Blueprint Solution. Any script or application that uses an authenticator makes a call to an Azure Key Vault container prior to each use. Access to Azure Key Vault containers is audited, which allows detection of violations of this prohibition if a service account is used to access a system without a corresponding call to the Azure Key Vault container

A Key Vault is deployed as a part of the predeployment process -- [see script here](https://github.com/AppliedIS/azure-blueprint/blob/master/predeploy/Orchestration_InitialSetup.ps1)

As a part of the predeployment process, specific keys are uploaded to the key vault that will be needed for the rest of the deployment process

## Keys Uploaded to Key Vault

1) Azure Username - username that will be used for specific DSC configuration scripts used to manipulate and configure Azure resources
2) Azure Password - password associated with Azure Username
3) Admin Password - password used for Administrator accounts on all machines
4) Encryption Key Url - key URL need for disk encryption
5) Azure Active Directory Client ID
6) Azure Active Directory Client Secret
