### ISSUE TITLE
Orchestration script user experience improvement

### ISSUE THREAD

**Issue by jomolesk** [AppliedIS/azure-blueprint#92]
** **UPDATED** ** 

Update script functionality to better guide users + clean up script code

** order parameter inputs

- azureUserName (note: consistency with other "Username/UserName")
- azurePassword

Re-prompt for valid user/password if error (currently script returns error but continues to run).

- subscriptionID

- adminUsername (note: consistency with other "Username/UserName") ** do we need this here? **
- adminPassword ** do we need this here? **
- sqlServerServiceAccountPassword

- resourceGroupName
- keyVaultName
- aadAppName ** can we just assign a default + 4 random chars? **

- keyEncryptionKeyName ** do not prompt for this; use a default **

** general clean-up

suppress extraneous output [cmdlet orchestration...] (if possible)
![image](https://user-images.githubusercontent.com/23081194/27185680-19eb373e-51b4-11e7-8b71-6cb1edd66e79.png)

update output to reflect current implementation
![image](https://user-images.githubusercontent.com/23081194/27185975-fb4a5c8c-51b4-11e7-8900-0db6a07d644e.png)

**Comment by jomolesk** [comment]
![image](https://user-images.githubusercontent.com/23081194/27435487-5cd42256-572a-11e7-9965-fb3f0f4db3ea.png)

**Comment by jomolesk** [comment]
![image](https://user-images.githubusercontent.com/23081194/27435548-8445bbce-572a-11e7-99aa-d9bb9a208a98.png)

**Comment by jomolesk** [comment]
Additional comment from tester:
[string]$recoveryServicesAADServicePrincipalName = "ff281ffe-705c-4f53-9f37-a40e6f2c68f3", What is this SID? Is there a reason it’s used?

**Comment by manishkumar-agarwal** [comment]
HI @jomolesk,

Parameters recoveryServicesAADServicePrincipalName ,  keyEncryptionKeyName  and aadAppName  have been removed from preorchestration script.

Thanks

**Comment by jomolesk** [comment]
There's an error w/ the scrip if when a password doesn't meet all the complexity requirements and a compliant password is subsequenty entered:

![image](https://user-images.githubusercontent.com/23081194/27867354-66a5c978-6167-11e7-866d-5e034fc4a4f4.png)

**Comment by manishkumar-agarwal** [comment]
Hi @jomolesk 

Is this the latest Orchestration script? I ran the script today and it ran fine.

**Comment by davoodharun** [comment]
I've made some updates here: https://github.com/AppliedIS/azure-blueprint/blob/reconfigure/predeploy/Orchestration_InitialSetup.ps1

I am in the process of merging it into master
