### ISSUE TITLE
OMS Monitoring Agent Extension fails intermittently on different VMs (EnterpriseCloudMonitoring)

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#95]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'EnterpriseCloudMonitoring'. Error message: \\\"Operation Failed: 9ad96a5d-b3ff-4428-91de-e1ea33fa6747 is currently connected to a different Azure Cloud, and updating the cloud type is not supported. Please login to the machine, disconnect the workspace, and try again.\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by davoodharun** [comment]
![image](https://user-images.githubusercontent.com/12518929/27335462-7b45b600-559a-11e7-9760-09e6f6eacdaf.png)

**Comment by davoodharun** [comment]
Although the extension fails, the computer still gets connected to OMS.

![image](https://user-images.githubusercontent.com/12518929/27335557-dea1b244-559a-11e7-9d68-ff823b737725.png)

**Comment by davoodharun** [comment]
Provisioning is done through arm template:
```
{
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "name": "[concat(parameters('vmName'), '/EnterpriseCloudMonitoring')]",
            "apiVersion": "2015-06-15",
            "location": "[resourceGroup().location]",
            "dependsOn": [],
            "properties": {
                "publisher": "Microsoft.EnterpriseCloud.Monitoring",
                "type": "MicrosoftMonitoringAgent",
                "typeHandlerVersion": "1.0",
                "autoUpgradeMinorVersion": true,
                "settings": {
                    "workspaceId": "[reference(resourceId('Microsoft.OperationalInsights/workspaces/', parameters('workspaceName')), '2015-03-20').customerId]"
                },
                "protectedSettings": {
                    "workspaceKey": "[listKeys(resourceId('Microsoft.OperationalInsights/workspaces/', parameters('workspaceName')), '2015-03-20').primarySharedKey]"
                }
            }
        }
```

**Comment by haitch** [comment]
this issue should be solved by now, we just published the newer version of the extension.

**Comment by davoodharun** [comment]
@haitch thank you! I will test tonight

**Comment by davoodharun** [comment]
confirmed this as resolved.
