### ISSUE TITLE
OMS agent connectivity is blocked on SQL, web tier VMs

### ISSUE THREAD

**Issue by jomolesk** [AppliedIS/azure-blueprint#98]
May be related to NSG ruleset.

The OMS Agent extension for Windows requires that the target virtual machine is connected to the internet. ([ref](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/extensions-oms))

**Comment by davoodharun** [comment]
@jomolesk are you opening this issue with respect to #95 ?

**Comment by jomolesk** [comment]
I don't think it's related.
